# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QuantitéDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(438, 249)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("background-color:#ffeeea;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color:#ff978d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("border:None;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(-1, 4, 4, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.closeButton = QtWidgets.QPushButton(self.frame_4)
        self.closeButton.setMinimumSize(QtCore.QSize(40, 20))
        self.closeButton.setMaximumSize(QtCore.QSize(40, 20))
        self.closeButton.setStyleSheet("QPushButton { background: transparent; border:0px; } \n"
"QPushButton:hover {background-color:#ff6f61;color:white;border-radius:2px}")
        self.closeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/croce.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.verticalLayout_2.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("border:None;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.quantiteLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.quantiteLineEdit.setMinimumSize(QtCore.QSize(300, 40))
        self.quantiteLineEdit.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quantiteLineEdit.setFont(font)
        self.quantiteLineEdit.setStyleSheet("QLineEdit {   \n"
"   border-width:2px;\n"
"   border-radius:10px;\n"
"   border-style:solid;\n"
"   border-color:#ff978d;\n"
"   color: #635f72\n"
" } ")
        self.quantiteLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.quantiteLineEdit.setObjectName("quantiteLineEdit")
        self.horizontalLayout.addWidget(self.quantiteLineEdit)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("border:None;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.validerButton = QtWidgets.QPushButton(self.frame_3)
        self.validerButton.setMinimumSize(QtCore.QSize(200, 40))
        self.validerButton.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.validerButton.setFont(font)
        self.validerButton.setStyleSheet("QPushButton {border-radius : 10px ; border: 1px #1f528d ; background-color: #e66558; color:white;} QPushButton:pressed {background-color: #ff7c6f;}")
        self.validerButton.setObjectName("validerButton")
        self.horizontalLayout_2.addWidget(self.validerButton)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.quantiteLineEdit.setPlaceholderText(_translate("Dialog", "Quantité :"))
        self.validerButton.setText(_translate("Dialog", "Valider"))
