# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RecetteDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog2(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1002, 792)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 30))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: #ffeeea;  \n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-color: #ff978d;\n"
"    border-bottom:none;\n"
"}\n"
"\n"
"QFrame {\n"
"    border-color: #ff978d;\n"
"    background-color: #fee2db;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    border-bottom: 2px solid #ff978d;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(250, 0, 0, 5)
        self.horizontalLayout.setSpacing(200)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hotbar_mouv = QtWidgets.QFrame(self.widget)
        self.hotbar_mouv.setStyleSheet("")
        self.hotbar_mouv.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hotbar_mouv.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hotbar_mouv.setObjectName("hotbar_mouv")
        self.horizontalLayout.addWidget(self.hotbar_mouv)
        self.closeButonFrame = QtWidgets.QFrame(self.widget)
        self.closeButonFrame.setMinimumSize(QtCore.QSize(50, 30))
        self.closeButonFrame.setMaximumSize(QtCore.QSize(50, 30))
        self.closeButonFrame.setStyleSheet("border:None;\n"
"background-color:transparent;")
        self.closeButonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.closeButonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.closeButonFrame.setObjectName("closeButonFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.closeButonFrame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.closeButton = QtWidgets.QPushButton(self.closeButonFrame)
        self.closeButton.setMinimumSize(QtCore.QSize(40, 20))
        self.closeButton.setMaximumSize(QtCore.QSize(40, 20))
        self.closeButton.setStyleSheet("QPushButton { background: transparent; border:0px; } \n"
"QPushButton:hover {background-color:#ff6f61;color:white;border-radius:2px}")
        self.closeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/croce.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_7.addWidget(self.closeButton)
        self.horizontalLayout.addWidget(self.closeButonFrame)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setStyleSheet("background-color:#ffeeea;  \n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color:#ff978d;\n"
"border-top:None;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(60, 20, 60, 80)
        self.verticalLayout_4.setSpacing(50)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setStyleSheet("border-radius:20px;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color:#ff978d;\n"
"background-color:#fee2db;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.recipe_name_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.recipe_name_label.setFont(font)
        self.recipe_name_label.setStyleSheet("color: #837d99;\n"
"border:None;")
        self.recipe_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.recipe_name_label.setObjectName("recipe_name_label")
        self.horizontalLayout_3.addWidget(self.recipe_name_label)
        self.verticalLayout_4.addWidget(self.frame)
        self.AjoutFrame = QtWidgets.QFrame(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AjoutFrame.sizePolicy().hasHeightForWidth())
        self.AjoutFrame.setSizePolicy(sizePolicy)
        self.AjoutFrame.setStyleSheet("border-radius:50px;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color:#ff978d;\n"
"background-color:#fee2db;")
        self.AjoutFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AjoutFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AjoutFrame.setObjectName("AjoutFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.AjoutFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.AjoutFrame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_2.setStyleSheet("border:None;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(40, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet(" border-width:2px;\n"
"   border-radius:10px;\n"
"   border-style:solid;\n"
"   border-color:#ff978d;\n"
"   color: #837d99")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(self.AjoutFrame)
        self.frame_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_3.setStyleSheet("border:None;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(30, 10, 30, 0)
        self.horizontalLayout_6.setSpacing(60)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.instructionAjout = QtWidgets.QTextEdit(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.instructionAjout.setFont(font)
        self.instructionAjout.setStyleSheet("QTextEdit {   \n"
"   border-width:2px;\n"
"   border-radius:10px;\n"
"   border-style:solid;\n"
"   border-color:#ff978d;\n"
"   color: #635f72;\n"
"    background-color:#fee2db;\n"
" } ")
        self.instructionAjout.setReadOnly(True)
        self.instructionAjout.setObjectName("instructionAjout")
        self.horizontalLayout_6.addWidget(self.instructionAjout)
        self.ingredientAjout = QtWidgets.QTextEdit(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.ingredientAjout.setFont(font)
        self.ingredientAjout.setStyleSheet("QTextEdit {   \n"
"   border-width:2px;\n"
"   border-radius:10px;\n"
"   border-style:solid;\n"
"   border-color:#ff978d;\n"
"   color: #635f72;\n"
"    background-color:#fee2db;\n"
" } ")
        self.ingredientAjout.setReadOnly(True)
        self.ingredientAjout.setObjectName("ingredientAjout")
        self.horizontalLayout_6.addWidget(self.ingredientAjout)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.AjoutFrame)
        self.frame_4.setMinimumSize(QtCore.QSize(42, 42))
        self.frame_4.setMaximumSize(QtCore.QSize(42, 42))
        self.frame_4.setStyleSheet("border:None;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.poubelleButon = QtWidgets.QPushButton(self.frame_4)
        self.poubelleButon.setMinimumSize(QtCore.QSize(40, 40))
        self.poubelleButon.setMaximumSize(QtCore.QSize(40, 40))
        self.poubelleButon.setStyleSheet("QPushButton { background: transparent; border:0px; } \n"
"QPushButton:hover {background-color:#ff6f61;color:white;border-radius:2px}")
        self.poubelleButon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/poubelle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.poubelleButon.setIcon(icon1)
        self.poubelleButon.setIconSize(QtCore.QSize(35, 35))
        self.poubelleButon.setObjectName("poubelleButon")
        self.horizontalLayout_2.addWidget(self.poubelleButon)
        self.verticalLayout_3.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.AjoutFrame)
        self.verticalLayout_2.addWidget(self.widget_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.recipe_name_label.setText(_translate("Dialog", "Label"))
        self.lineEdit.setText(_translate("Dialog", "1"))
        self.instructionAjout.setPlaceholderText(_translate("Dialog", "Instructions :"))
        self.ingredientAjout.setPlaceholderText(_translate("Dialog", "Ingrédients :"))
